Label: ['$\alpha_{s,fix}$', '$Q_0$', '$\ln\, c_1$', '$\ln\, c_2$', '$\tau_0$', '$\ln\, c_3$']
Ticks:
   - [0.1, 0.2, 0.3, 0.4]
   - [2, 4, 6, 8]
   - [-4, -2, 0, 2]
   - [-4, -2, 0, 2]
   - [0.0, 0.4, 0.8, 1.2]
   - [-2, 0, 2, 4]
Reorder: [0, 1]
Suffix: 'Small'

