
ObservablePlot:
   - Key: ['ALICE_2760_Hadron_ch_0_5', 'ALICE_2760_Hadron_ch_5_10', 'ALICE_2760_Hadron_ch_10_20', 'ALICE_2760_Hadron_ch_20_30', 'ALICE_2760_Hadron_ch_30_40', 'ALICE_2760_Hadron_ch_40_50']
     Suffix: 'ALICE_Hadron2760'
     Label: ['0-5%', '5-10%', '10-20%', '20-30%', '30-40%', '40-50%']
     Common: 'ALICE, 2.76 TeV, Charged Hadron'
   - Key: ['ALICE_2760_Hadron_pi0_0_10', 'ALICE_2760_Hadron_pi0_20_50']
     Suffix: 'ALICE_Pi02760'
     Label: ['0-10%', '20-50%']
     Common: 'ALICE, 2.76 TeV, $\pi^0$'
   - Key: ['ALICE_2760_Hadron_pi_0_5', 'ALICE_2760_Hadron_pi_5_10', 'ALICE_2760_Hadron_pi_10_20', 'ALICE_2760_Hadron_pi_20_40']
     Suffix: 'ALICE_Pi2760'
     Label: ['0-5%', '5-10%', '10-20%', '20-40%']
     Common: 'ALICE, 2.76 TeV, $\pi$'
   - Key: ['ALICE_2760_Jet_R02_0_10', 'ALICE_2760_Jet_R02_10_30']
     Suffix: 'ALICE_Jet2760'
     Label: ['0-10%', '10-30%']
     Common: 'ALICE, 2.76 TeV, Jet R = 0.2'
   - Key: ['ALICE_5020_Hadron_ch_0_5', 'ALICE_5020_Hadron_ch_5_10', 'ALICE_5020_Hadron_ch_10_20', 'ALICE_5020_Hadron_ch_20_30', 'ALICE_5020_Hadron_ch_30_40', 'ALICE_5020_Hadron_ch_40_50']
     Suffix: 'ALICE_Hadron5020'
     Label: ['0-5%', '5-10%', '10-20%', '20-30%', '30-40%', '40-50%']
     Common: 'ALICE, 5.02 TeV, Charged Hadron'
   - Key: ['ALICE_5020_Hadron_pi_0_5', 'ALICE_5020_Hadron_pi_5_10', 'ALICE_5020_Hadron_pi_10_20', 'ALICE_5020_Hadron_pi_20_30', 'ALICE_5020_Hadron_pi_30_40', 'ALICE_5020_Hadron_pi_40_50']
     Suffix: 'ALICE_Pi5020'
     Label: ['0-5%', '5-10%', '10-20%', '20-30%', '30-40%', '40-50%']
     Common: 'ALICE, 5.02 TeV, $\pi$'
   - Key: ['ALICE_5020_Jet_R02_0_10', 'ALICE_5020_Jet_R04_0_10']
     Suffix: 'ALICE_Jet5020'
     Label: ['R = 0.2', 'R = 0.4']
     Common: 'ALICE, 5.02 TeV, Jet, 0-10%'
   - Key: ['ATLAS_2760_Hadron_ch_0_5', 'ATLAS_2760_Hadron_ch_5_10', 'ATLAS_2760_Hadron_ch_10_20', 'ATLAS_2760_Hadron_ch_20_30', 'ATLAS_2760_Hadron_ch_30_40', 'ATLAS_2760_Hadron_ch_40_50']
     Suffix: 'ATLAS_Hadron2760'
     Label: ['0-5%', '5-10%', '10-20%', '20-30%', '30-40%', '40-50%']
     Common: 'ATLAS, 2.76 TeV, Charged Hadron'
   - Key: ['ATLAS_2760_Jet_R04_0_10', 'ATLAS_2760_Jet_R04_10_20', 'ATLAS_2760_Jet_R04_20_30', 'ATLAS_2760_Jet_R04_30_40', 'ATLAS_2760_Jet_R04_40_50']
     Suffix: 'ATLAS_Jet2760'
     Label: ['0-10%', '10-20%', '20-30%', '30-40%', '40-50%']
     Common: 'ATLAS, 2.76 TeV, Jet R = 0.4'
   - Key: ['ATLAS_5020_Jet_R04_0_10', 'ATLAS_5020_Jet_R04_10_20', 'ATLAS_5020_Jet_R04_20_30', 'ATLAS_5020_Jet_R04_30_40', 'ATLAS_5020_Jet_R04_40_50']
     Suffix: 'ATLAS_Jet5020'
     Label: ['0-10%', '10-20%', '20-30%', '30-40%', '40-50%']
     Common: 'ATLAS, 5.02 TeV, Jet R = 0.4'
   - Key: ['CMS_2760_Hadron_ch_0_5', 'CMS_2760_Hadron_ch_5_10', 'CMS_2760_Hadron_ch_10_30']
     Suffix: 'CMS_Hadron2760'
     Label: ['0-5%', '5-10%', '10-30%']
     Common: 'CMS, 2.76 TeV, Charged Hadron'
   - Key: ['CMS_2760_Jet_R02_0_5', 'CMS_2760_Jet_R02_5_10', 'CMS_2760_Jet_R02_10_30', 'CMS_2760_Jet_R02_30_50']
     Suffix: 'CMS_Jet2760R02'
     Label: ['0-5%', '5-10%', '10-30%', '30-50%']
     Common: 'CMS, 2.76 TeV, Jet R = 0.2'
   - Key: ['CMS_2760_Jet_R03_0_5', 'CMS_2760_Jet_R03_5_10', 'CMS_2760_Jet_R03_10_30', 'CMS_2760_Jet_R03_30_50']
     Suffix: 'CMS_Jet2760R03'
     Label: ['0-5%', '5-10%', '10-30%', '30-50%']
     Common: 'CMS, 2.76 TeV, Jet R = 0.3'
   - Key: ['CMS_2760_Jet_R04_0_5', 'CMS_2760_Jet_R04_5_10', 'CMS_2760_Jet_R04_10_30', 'CMS_2760_Jet_R04_30_50']
     Suffix: 'CMS_Jet2760R04'
     Label: ['0-5%', '5-10%', '10-30%', '30-50%']
     Common: 'CMS, 2.76 TeV, Jet R = 0.4'
   - Key: ['CMS_5020_Hadron_ch_0_5', 'CMS_5020_Hadron_ch_5_10', 'CMS_5020_Hadron_ch_10_30', 'CMS_5020_Hadron_ch_30_50']
     Suffix: 'CMS_Hadron5020'
     Label: ['0-5%', '5-10%', '10-30%', '30-50%']
     Common: 'CMS, 5.02 TeV, Charged Hadron'
   - Key: ['CMS_5020_Jet_R02_0_10', 'CMS_5020_Jet_R02_10_30', 'CMS_5020_Jet_R02_30_50']
     Suffix: 'CMS_Jet5020R02'
     Label: ['0-10%', '10-30%', '30-50%']
     Common: 'CMS, 5.02 TeV, Jet R = 0.2'
   - Key: ['CMS_5020_Jet_R03_0_10', 'CMS_5020_Jet_R03_10_30', 'CMS_5020_Jet_R03_30_50']
     Suffix: 'CMS_Jet5020R03'
     Label: ['0-10%', '10-30%', '30-50%']
     Common: 'CMS, 5.02 TeV, Jet R = 0.3'
   - Key: ['CMS_5020_Jet_R04_0_10', 'CMS_5020_Jet_R04_10_30', 'CMS_5020_Jet_R04_30_50']
     Suffix: 'CMS_Jet5020R04'
     Label: ['0-10%', '10-30%', '30-50%']
     Common: 'CMS, 5.02 TeV, Jet R = 0.4'
   - Key: ['CMS_5020_Jet_R06_0_10', 'CMS_5020_Jet_R06_10_30', 'CMS_5020_Jet_R06_30_50']
     Suffix: 'CMS_Jet5020R06'
     Label: ['0-10%', '10-30%', '30-50%']
     Common: 'CMS, 5.02 TeV, Jet R = 0.6'
   - Key: ['CMS_5020_Jet_R08_0_10', 'CMS_5020_Jet_R08_10_30', 'CMS_5020_Jet_R08_30_50']
     Suffix: 'CMS_Jet5020R08'
     Label: ['0-10%', '10-30%', '30-50%']
     Common: 'CMS, 5.02 TeV, Jet R = 0.8'
   - Key: ['CMS_5020_Jet_R10_0_10', 'CMS_5020_Jet_R10_10_30', 'CMS_5020_Jet_R10_30_50']
     Suffix: 'CMS_Jet5020R10'
     Label: ['0-10%', '10-30%', '30-50%']
     Common: 'CMS, 5.02 TeV, Jet R = 1.0'
   - Key: ['PHENIX_200_Hadron_pi0_0_10', 'PHENIX_200_Hadron_pi0_10_20', 'PHENIX_200_Hadron_pi0_20_30', 'PHENIX_200_Hadron_pi0_30_40', 'PHENIX_200_Hadron_pi0_40_50']
     Suffix: 'PHENIX_Pi0200'
     Label: ['0-10%', '10-20%', '20-30%', '30-40%', '40-50%']
     Common: 'PHENIX, 200 GeV, pi0'
   - Key: ['STAR_200_Hadron_ch_0_5', 'STAR_200_Hadron_ch_10_20', 'STAR_200_Hadron_ch_20_30', 'STAR_200_Hadron_ch_30_40']
     Suffix: 'STAR_Hadron200'
     Label: ['0-5%', '10-20%', '20-30%', '30-40%']
     Common: 'STAR, 200 GeV, Charged Hadron'
   - Key: ['STAR_200_ChargedJet_R02_0_10', 'STAR_200_ChargedJet_R04_0_10']
     Suffix: 'STAR_ChargedJet200'
     Label: ['R = 0.2', 'R = 0.4']
     Common: 'STAR, 200 GeV, Charged Jet, 0-10%'






